name: CI

on:
  pull_request:
    branches: [ develop, main ]
  push:
    branches: [ develop ]

jobs:
  build-and-test:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Show Xcode version
        run: xcodebuild -version

      - name: List targets (debug)
        run: xcodebuild -list -project Workoutlog.xcodeproj

      - name: Build & test
        run: |
          set -o pipefail
          xcodebuild \
            -project Workoutlog.xcodeproj \
            -scheme Workoutlog \
            -destination 'platform=iOS Simulator,name=iPhone 16' \
            -configuration Debug \
            clean test | xcpretty
        env:
          NSUnbufferedIO: YES

  lint:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Install SwiftLint
        run: brew install swiftlint
      - name: Run SwiftLint
        run: swiftlint --strict || true  # allow warnings initially
