name: CI

on:
  pull_request:
    branches: [ develop, main ]
  push:
    branches: [ develop ]

jobs:
  build-and-test:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Show Xcode version
        run: xcodebuild -version

      - name: List targets (debug)
        run: xcodebuild -list -project Workoutlog.xcodeproj

      - name: Show available destinations
        run: xcodebuild -project Workoutlog.xcodeproj -scheme Workoutlog -showdestinations || true

      - name: Build & test (iPhone 15 Simulator)
        run: |
          set -o pipefail
          # iOS 버전을 명시하여 destination을 더 구체적으로 지정합니다.
          # 현재 macos-14 최신 Xcode 기준 iOS 17.5 버전이 주로 사용됩니다.
          xcodebuild \
            -project Workoutlog.xcodeproj \
            -scheme Workoutlog \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' \
            -configuration Debug \
            clean test
        env:
          NSUnbufferedIO: YES

  lint:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Install SwiftLint
        run: brew install swiftlint
      - name: Run SwiftLint
        run: swiftlint --strict || true  # allow warnings initially
